# Generated by Django 6.0.7 on 2026-08-21 16:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=20, unique=True)),
                ('nome', models.CharField(max_length=150)),
                ('telefone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('data_nascimento', models.DateField()),
                ('modalidade', models.CharField(choices=[('MINI', 'Mini Sprint — 500m natação + 2,5km corrida'), ('SPRINT', 'Sprint — 1km natação + 5km corrida')], max_length=10)),
                ('militar', models.BooleanField(default=False)),
                ('comprovante_militar', models.FileField(blank=True, null=True, upload_to='comprovantes/militares/')),
                ('autorizacao_responsavel', models.FileField(blank=True, null=True, upload_to='comprovantes/responsaveis/')),
                ('lote', models.CharField(blank=True, max_length=30)),
                ('valor_inscricao', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('taxa_servico', models.DecimalField(decimal_places=2, default=Decimal('6.80'), max_digits=8)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('status', models.CharField(choices=[('PENDENTE', 'Aguardando pagamento'), ('PAGO', 'Pagamento confirmado'), ('CANCELADO', 'Cancelada')], default='PENDENTE', max_length=12)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Inscrição',
                'verbose_name_plural': 'Inscrições',
                'ordering': ['-criado_em'],
            },
        ),
    ]
