# Generated by Django 6.0.8 on 2026-08-25 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscricao',
            name='taxa_servico',
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='lote',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plataforma', models.CharField(default='MERCADO_PAGO', max_length=30)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('link_pagamento', models.URLField(max_length=1000)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('CANCELADO', 'Cancelado'), ('EXPIRADO', 'Expirado')], default='PENDENTE', max_length=12)),
                ('metodo', models.CharField(blank=True, max_length=30)),
                ('identificador_transacao', models.CharField(blank=True, max_length=150)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('pago_em', models.DateTimeField(blank=True, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('inscricao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pagamento', to='inscricoes.inscricao')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
