# Generated by Django 6.0.8 on 2026-08-26 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0002_remove_inscricao_taxa_servico_alter_inscricao_lote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='identificador_transacao',
            field=models.CharField(blank=True, db_index=True, max_length=150),
        ),
    ]
