# Generated by Django 6.0.8 on 2026-09-04 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0004_fornecedor_contareceber_contapagar'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='tamanho_camisa',
            field=models.CharField(blank=True, choices=[('PP', 'PP'), ('P', 'P'), ('M', 'M'), ('G', 'G'), ('GG', 'GG'), ('XG', 'XG'), ('2XG', '2XG'), ('3XG', '3XG')], default='', max_length=3, verbose_name='Tamanho da camisa'),
        ),
    ]
