# Generated by Django 6.0.8 on 2026-09-05 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0005_inscricao_tamanho_camisa'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='token_publico',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True),
        ),
    ]
