# Generated by Django 6.0.8 on 2026-09-05 10:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0007_preencher_tokens_publicos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao',
            name='token_publico',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
