# Generated by Django 6.0.8 on 2026-09-18 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0008_alter_inscricao_token_publico'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='comprovante_pcd',
            field=models.FileField(blank=True, null=True, upload_to='comprovantes/pcd/', verbose_name='Documento comprobatório PCD'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='pcd',
            field=models.BooleanField(default=False, verbose_name='Atleta PCD'),
        ),
    ]
